services:
  frontend:
    container_name: "frontend"
    build:
      context: .
      dockerfile: Dockerfile
    image: manutencao_comunitaria_front:0.0.1
    restart: always
    networks:
      - mnt_com_network
      - web

networks:
  mnt_com_network:
    external: true
  traefik_network:
    external: true
