services:
  frontend:
    container_name: "frontend"
    build:
      context: .
      dockerfile: Dockerfile
    image: manutencao_comunitaria_front:0.0.1
    restart: always
    networks:
      - mnt_com_network
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.mconde.dev.br`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

networks:
  mnt_com_network:
    external: true
  web:
    external: true
